# Generated by Django 5.0.7 on 2024-07-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
    ]
